version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000 # This exposes the web service on localhost:3000
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        MOD_PATH: ./apps/api
        SRC_PATH: ./apps/api
    restart: always
    expose:
      - 3001 # This makes the api service accessible within the Docker network
    networks:
      - app_network

networks:
  app_network:
    driver: bridge # This creates an internal network for the containers